### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hmm-star** [Vort3xed/QuizletPaywallSupplement#1]
the remove blue feature is not working

**Comment by Vort3xed** [comment]
Could you try to be more specific? What browser are you using, what was the message on the screen when you tried using the extension, and could you provide a screenshot of the page?

Thanks for letting me know though, I'll check if the extension is still working.

**Comment by hmm-star** [comment]
i am using Brave browser latest  build. There is no message on the screen whatsoever, when i click on the `remove blur` and `remove email verification` buttons by clicking on the extension, it does not work/nothing happens.

**Comment by hmm-star** [comment]
any update ?

**Comment by Vort3xed** [comment]
My apologies for the delay. The extension should be fixed now.

**Comment by Vort3xed** [comment]
I had to update the manifest version from 2 to 3.

**Comment by hmm-star** [comment]
hi
the extension not working. I could not bypass email verification and it could not remove the blue from the answers. Please check it
